<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_source</name>
   <tag></tag>
   <elementGuidId>9b40054d-2d7f-41e2-94fa-bc24f92a7149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.lbl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-div']/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e1ad8042-94f0-406d-8960-7721c028f8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbl</value>
      <webElementGuid>a69b017b-7a01-4579-969c-83a580fc315c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>src</value>
      <webElementGuid>81491686-f6df-43d3-b04f-e1a6d709f100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>source</value>
      <webElementGuid>b9dd8267-752a-48e2-80bc-edd9ad59f951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-div&quot;)/div[@class=&quot;search-wrapper&quot;]/div[@class=&quot;source input-box&quot;]/label[@class=&quot;lbl&quot;]</value>
      <webElementGuid>5f11f31b-3e75-467f-a5ce-bd7d53cfdc7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-div']/div/div/label</value>
      <webElementGuid>ecac48a3-4dcd-41f8-b6b8-c30fedd004d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>da3686d7-0795-4419-86d3-131d9f4d5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'source' or . = 'source')]</value>
      <webElementGuid>0ede6fbb-e506-42a2-befd-21bd415c511c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
