<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Espanol (1)</name>
   <tag></tag>
   <elementGuidId>42267917-8cdb-4c5b-ba71-06ceaa7a4119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.config-option-lang.config-options.chosen > span.cli.flag-centre > span.w-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hc']/div/ul/li[2]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b25c2ddd-290b-412c-812d-d6f6ba455729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-50</value>
      <webElementGuid>ca6ab9b7-6cd1-4bab-9dde-03d858a57c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Espanol
                                    </value>
      <webElementGuid>f6d6f5ab-e904-4968-97a4-a8434b5390bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang_dd&quot;)/div[@class=&quot;icon-down icon ich dib&quot;]/div[@id=&quot;hc&quot;]/div[1]/ul[@class=&quot;rdc-langlist&quot;]/li[@class=&quot;config-option-lang config-options  chosen&quot;]/span[@class=&quot;cli flag-centre&quot;]/span[@class=&quot;w-50&quot;]</value>
      <webElementGuid>52671c15-7baa-46c9-bf01-2f7fcee136be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hc']/div/ul/li[2]/span/span[2]</value>
      <webElementGuid>5444b5d2-5157-474a-aba3-ba37713fdd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/span/span[2]</value>
      <webElementGuid>f812fb7d-6e79-46d8-838d-7cec176b71d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                        Espanol
                                    ' or . = '
                                        Espanol
                                    ')]</value>
      <webElementGuid>c57ca42d-ae9c-4b7a-81eb-ecab74b2bcd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
