<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_flags</name>
   <tag></tag>
   <elementGuidId>3790a7ab-f646-4756-9221-f6fefdd0052b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.flags</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lang_chosen']/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8668ca44-ca15-4ccd-9feb-feb924895900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c1c3e960-bed5-49f0-b083-b8bc446f4d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flags</value>
      <webElementGuid>3c7d03a7-8273-4a92-97b0-9d84ef7c3b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../images/US.png</value>
      <webElementGuid>7f88dbcd-665e-4e5b-bcad-1ae3cd279348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang_chosen&quot;)/picture[1]/img[@class=&quot;flags&quot;]</value>
      <webElementGuid>8ef626c0-4330-4fb9-b2ca-5fd7620f0d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lang_chosen']/picture/img</value>
      <webElementGuid>621e3160-d031-4617-8b51-f756aec69768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>222f23ed-5504-4d49-bf4c-461d36d6737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../images/US.png']</value>
      <webElementGuid>f9f5e57d-9a83-48dd-b7e6-742719df7603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
