<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_English</name>
   <tag></tag>
   <elementGuidId>69a892d0-bd05-4db6-b768-f1d5ce2317a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.w-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hc']/div/ul/li/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3a67654-5868-406a-a86d-6cd5fb2a11b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-50</value>
      <webElementGuid>3ca914c3-06ef-4402-a5c6-3d1b1439be24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        English
                                    </value>
      <webElementGuid>cdd75d2e-8d69-485b-b2f8-faa2ff8954e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang_dd&quot;)/div[@class=&quot;icon-down icon ich dib&quot;]/div[@id=&quot;hc&quot;]/div[1]/ul[@class=&quot;rdc-langlist&quot;]/li[@class=&quot;config-option-lang config-options  chosen&quot;]/span[@class=&quot;cli flag-centre&quot;]/span[@class=&quot;w-50&quot;]</value>
      <webElementGuid>3d25a37e-75b9-4943-bf0a-d85d6f3f182d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hc']/div/ul/li/span/span[2]</value>
      <webElementGuid>c7784738-a065-41b5-bccd-5b7f2023ba91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/span/span[2]</value>
      <webElementGuid>3c01378a-a6a3-4009-adfb-1f769b4b3d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                        English
                                    ' or . = '
                                        English
                                    ')]</value>
      <webElementGuid>6b980186-e595-4236-a519-741e6b419966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
